//Para insertar los paises en el option de Pais de residencia.
const $optionPaises = document.getElementById("paises_select");
////Un fragment para no modificar el DOM por cada uno de los paises.
const $fragmento = document.createDocumentFragment();
export const paises = [
	"Afganistán",
	"Albania",
	"Alemania",
	"Andorra",
	"Angola",
	"Antigua y Barbuda",
	"Arabia Saudita",
	"Argelia",
	"Argentina",
	"Armenia",
	"Australia",
	"Austria",
	"Azerbaiyán",
	"Bahamas",
	"Bangladés",
	"Barbados",
	"Baréin",
	"Bélgica",
	"Belice",
	"Benín",
	"Bielorrusia",
	"Birmania",
	"Bolivia",
	"Bosnia y Herzegovina",
	"Botsuana",
	"Brasil",
	"Brunéi",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Bután",
	"Cabo Verde",
	"Camboya",
	"Camerún",
	"Canadá",
	"Catar",
	"Chad",
	"Chile",
	"China",
	"Chipre",
	"Ciudad del Vaticano",
	"Colombia",
	"Comoras",
	"Congo",
	"Corea del Norte",
	"Corea del Sur",
	"Costa de Marfil",
	"Costa Rica",
	"Croacia",
	"Cuba",
	"Dinamarca",
	"Dominica",
	"Ecuador",
	"Egipto",
	"El Salvador",
	"Emiratos Árabes Unidos",
	"Eritrea",
	"Eslovaquia",
	"Eslovenia",
	"España",
	"Estados Unidos",
	"Estonia",
	"Esuatini",
	"Etiopía",
	"Filipinas",
	"Finlandia",
	"Fiyi",
	"Francia",
	"Gabón",
	"Gambia",
	"Georgia",
	"Ghana",
	"Granada",
	"Grecia",
	"Guatemala",
	"Guyana",
	"Guinea",
	"Guinea-Bisáu",
	"Guinea Ecuatorial",
	"Haití",
	"Honduras",
	"Hungría",
	"India",
	"Indonesia",
	"Irak",
	"Irán",
	"Irlanda",
	"Islandia",
	"Islas Marshall",
	"Islas Salomón",
	"Israel",
	"Italia",
	"Jamaica",
	"Japón",
	"Jordania",
	"Kazajistán",
	"Kenia",
	"Kirguistán",
	"Kiribati",
	"Kuwait",
	"Laos",
	"Lesoto",
	"Letonia",
	"Líbano",
	"Liberia",
	"Libia",
	"Liechtenstein",
	"Lituania",
	"Luxemburgo",
	"Macedonia del Norte",
	"Madagascar",
	"Malasia",
	"Malaui",
	"Maldivas",
	"Malí",
	"Malta",
	"Marruecos",
	"Mauricio",
	"Mauritania",
	"México",
	"Micronesia",
	"Moldavia",
	"Mónaco",
	"Mongolia",
	"Montenegro",
	"Mozambique",
	"Namibia",
	"Nauru",
	"Nepal",
	"Nicaragua",
	"Níger",
	"Nigeria",
	"Noruega",
	"Nueva Zelanda",
	"Omán",
	"Países Bajos",
	"Pakistán",
	"Palaos",
	"Panamá",
	"Papúa Nueva Guinea",
	"Paraguay",
	"Perú",
	"Polonia",
	"Portugal",
	"Reino Unido",
	"República Centroafricana",
	"República Checa",
	"República del Congo",
	"República Democrática del Congo",
	"República Dominicana",
	"Ruanda",
	"Rumania",
	"Rusia",
	"Samoa",
	"San Cristóbal y Nieves",
	"San Marino",
	"San Vicente y las Granadinas",
	"Santa Lucía",
	"Santo Tomé y Príncipe",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leona",
	"Singapur",
	"Siria",
	"Somalia",
	"Sri Lanka",
	"Sudáfrica",
	"Sudán",
	"Sudán del Sur",
	"Suecia",
	"Suiza",
	"Surinam",
	"Tailandia",
	"Tanzania",
	"Tayikistán",
	"Timor Oriental",
	"Togo",
	"Tonga",
	"Trinidad y Tobago",
	"Túnez",
	"Turkmenistán",
	"Turquía",
	"Tuvalu",
	"Ucrania",
	"Uganda",
	"Uruguay",
	"Uzbekistán",
	"Vanuatu",
	"Venezuela",
	"Vietnam",
	"Yemen",
	"Yibuti",
	"Zambia",
	"Zimbabue",
];

paises.forEach((pais) => {
	const opcion = document.createElement("option");
	opcion.value = pais;
	opcion.textContent = pais;
	if (pais === "Argentina") {
		opcion.selected = true;
	}
	$fragmento.appendChild(opcion);
});
if ($optionPaises) {
	$optionPaises.appendChild($fragmento);
}
